FROM mcr.microsoft.com/java/jdk:8-zulu-alpine as FIRST
COPY /source /usr/src/uygulama
WORKDIR /usr/src/uygulama
RUN javac uygulama.java

FROM mcr.microsoft.com/java/jre:8-zulu-alpine as SECOND
WORKDIR /uygulama
COPY --from=FIRST /usr/src/uygulama .
CMD ["java", "uygulama"]
